name: 'Corekaburra_test_suite'
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: 'Install dependencies'
        run: pip install -r requirements-dev.txt
      - name: 'Install Corekaburra'
        run: pip install .
      - name: 'Run unit tests'
        run: bash .travis/unit-test.sh
      - name: 'Run functional tests'
        run: bash functional_tests/Corekaburra-test.sh -p Corekaburra -d functional_tests/test_data -v
      - name: 'Run GFF annotation functional tests'
        run: bash annotation_n_gff_functional_tests/run_tests.sh -v
