name: 'Test'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: 'Install dependencies'
        run: pip install -r requirements-dev.txt
      - name: 'Install Corekaburra'
        run: pip install .
      - name: 'Run unit tests'
        run: bash .travis/unit-test.sh
      - name: 'Run functional tests'
        run: bash functional_tests/Corekaburra-test.sh -p Corekaburra -d functional_tests/test_data -v
      - name: 'Run GFF annotation functional tests'
        run: bash annotation_n_gff_functional_tests/run_tests.sh -v
